## 配置 Thymeleaf
# 编码
  spring:
    thymeleaf:
      encoding: utf-8
      cache: false
      mode: HTML5
    datasource:
      url:  jdbc:mysql://127.0.0.1:3306/brogger?serverTimezone=UTC&&characterEncoding=utf-8&useSSL=false
      username: root
      password: root
      driver-class-name: com.mysql.cj.jdbc.Driver
    jpa:
      show-sql: false
      hibernate:
        ddl-auto: update
    data:
      elasticsearch:
        cluster-name: localhost:9300
  ## 配置日志信息
  logging:
    pattern:
#      console: "%-d{yyyy-MM-dd HH:mm:ss} [ %p ] [ %c ] %m%n"
#      level: info
  debug: false
  server:
    port: 8080


#    ## 启动h2控制台
#    h2:
#      console:
#        enabled: true

# 配置文件服务器的地址
#com:
#   bloger:
#     fileServiceUrl: 'http://localhost:8081/upload'




